### ISSUE TITLE
Using as a dependency

### ISSUE THREAD

**Issue by LarsKrogJensen** [APIs-guru/graphql-voyager#44]
graphql-voyager 1.0.0-rc.9

I am trying to use this amazing component in a basic create-react-app but it is stuck on 'transmitting', the schema in the left sider loads fine though.

The chrome console logs a 'Uncaught SyntaxError: Unexpected token <'.

Here is a repo that reproduces the issue: https://github.com/LarsKrogJensen/voyager-issue44

The docs state a paragraph that I don't understand:
_Important: make sure to copy voyager.worker.js from node_modules/graphql-voyager/dist to the same folder as your main bundle._ 

Where in the demo-repo am I supposed to copy the file.

**Comment by RomanGotsiy** [comment]
Hey @LarsKrogJensen, thanks for detailed issue report and sorry for late reply!

> The chrome console logs a 'Uncaught SyntaxError: Unexpected token <'.

the reason for this issue is that Voyager tries to load `voyager.worker.js` but react-scripts return 404 page instead. I've checked docs for `react-scripts` and it seems GraphQL Voyager can't be used with it right now.

I will try to fix during next 1-2 days.

**Comment by LarsKrogJensen** [comment]
That would be awesome, many thanks in advance.

**Comment by LarsKrogJensen** [comment]
Lovely, now it works like a charm, closing the issue.
