### ISSUE TITLE
Ability to customize presets with custom endpoints

### ISSUE THREAD

**Issue by cabello** [APIs-guru/graphql-voyager#52]
Hi ❤️❤️❤️ !!! This gem is awesome and will be a game changer, I've used the live demo with custom schemas a few times already.

We run a microservices architecture and we are slowly moving the APIs from REST to GraphQL and I am considering having an internal version of Voyager running so anyone in our organization can introspect and learn about the APIs we have available.

It seems like the presets like Star Wars, Yelp, Shopify, and Github are hard-coded here https://github.com/APIs-guru/graphql-voyager/blob/master/src/presets.ts and the result of the introspection query are stored here https://github.com/APIs-guru/graphql-voyager/tree/master/src/introspection/presets. For demo purposes this makes total sense.

My feature request is: it would be nice to be able to list a series of endpoints and their names and have them listed in Voyager in the landing page, Voyager would then perform the introspection query and show the latest schema.

I would imagine something like the following:

```js
window.VOYAGER_PRESETS = {
  'clients': {url: 'https://clients.foo.com/api/graphql'},
  'accounts': {url: 'https://accounts.foo.com/v3/graph'},
  'orders': {url: 'https://orders-srv.foo.com/api/graphql'},
};
```

Related issues:
- https://github.com/APIs-guru/graphql-voyager/issues/4
- https://github.com/APIs-guru/graphql-voyager/issues/38

**Comment by IvanGoncharov** [comment]
@cabello We planned to move all options to float menu, see: https://github.com/APIs-guru/graphql-voyager/issues/32#issuecomment-321563571
After this will be done "landing page" will have only buttons for presets and "Custom introspection".
As I understand "Custom introspection" doesn't make sense in your use case so what will be left is a very simple component with a couple of buttons. 

So I think it would be better to just add a drop down list of presets to the floating menu.
In any case, I think this issue is blocked until we add float menu 😞

**Comment by IvanGoncharov** [comment]
@cabello Sorry for the delay.

We are finally separated Demo code from main Voyager so now you can provide your own widget for switching schemas (dropdown, radio button, etc.)
Here is how it's done in our demo:
https://github.com/APIs-guru/graphql-voyager/blob/489cdaff1abd0402ce90a23b115e9d3b1dfc6447/demo/index.tsx#L48-L56
