### ISSUE TITLE
"Change introspection" button missing on npm version.

### ISSUE THREAD

**Issue by kub1x** [APIs-guru/graphql-voyager#59]
Hey, probably a lame question. I've installed raphql-voyager via npm, but I don't see the "Change introspection" button. I see only graph for Query, but can't switch to Mutation view, which is what I thought the button is for. I could probably change it using `displayOptions.rootType`, but that would mean exposing two instances of voyager to see both Query and Mutation, right..?

**Comment by IvanGoncharov** [comment]
@kub1x Yes you right. We added "Change introspection" to showcase different APIs in Voyager and just added other settings there because it was easier.
As a proper solution, we want to add the floating menu with all settings on the main screen. Don't have any estimates but we still plan to work on it.
I'm closing this issue since it's duplication of #15
